---
- name: Expose Longhorn UI
  hosts: vm-1
  become: true
  tasks:
    - name: Patch Longhorn frontend service to use LoadBalancer
      shell: |
        kubectl patch svc longhorn-frontend -n longhorn-system -p '{"spec": {"type": "LoadBalancer"}}'

    - name: Get Longhorn LoadBalancer IP
      shell: kubectl -n longhorn-system get svc longhorn-frontend -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: longhorn_ip
      until: longhorn_ip.stdout != ""
      retries: 20
      delay: 10

    - name: Display Longhorn Access Info
      debug:
        msg: "Longhorn UI URL: http://{{ longhorn_ip.stdout }}"
