[master]
vm-1 ansible_host=192.168.252.107
vm-2 ansible_host=192.168.252.108
vm-3 ansible_host=192.168.252.109

; [node]
; vm-2 ansible_host=192.168.252.27
; vm-3 ansible_host=192.168.252.28

[all:vars]
ansible_user=ubuntu
ansible_password=123123
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
