[master]
vm-1 ansible_host=192.168.252.26
vm-2 ansible_host=192.168.252.27
vm-3 ansible_host=192.168.252.28

[node]
vm-4 ansible_host=192.168.252.29
vm-5 ansible_host=192.168.252.30

[all:vars]
ansible_user=ubuntu
ansible_password=123123
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
