#cloud-config
users:
  - name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, users
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$Ywzx/k7H3mdcqjvu$9.grQS5cpeplOwHMEf2Fbx2nrO7cbPuNYBRREpaT8n3j3Ql3/SapUKKCjUqA/1xfKrh.BoQaIztfCUMrvdYWf."
    ssh_authorized_keys:
      - ${SSH_KEY}
